<?php
define('MENU_NEW','New');
define('MENU_OPEN','Open');
define('MENU_SAVE','Save');
define('MENU_SAVE_AS','Save As');
define('MENU_DELETE','Delete');
define('MENU_SEND_PROJECT','Send Project');
define('MENU_SENT_ITEM','Sent Item');
define('MENU_PRINT','Print');
define('MENU_LOGOUT','Logout');

define('ZOOM','ZOOM');
define('UNTITLED_PROJECT_NAME','Untitled');

define('LEFTMENU_ADD_TABLE','Add Table');
define('LEFTMENU_CIRCULAR_TABLE','Circular Table');
define('LEFTMENU_SQUARE_TABLE','Square Table');
define('LEFTMENU_RECTANGULAR_TABLE','Rectangular Table');

define('LEFTMENU_ADD_FIGURE','Add Figure');
define('LEFTMENU_CIRCULAR_FIGURE','Circular');
define('LEFTMENU_SQUARE_FIGURE','Square');
define('LEFTMENU_RECTANGULAR_FIGURE','Add Table');

define('LEFTMENU_ADD_OTHER_TABLE','Add Other Room Items');

define('LEFTMENU_CIRCLE_TABLE_OPTIONS','Circular Table Options');
define('LEFTMENU_SQUARE_TABLE_OPTIONS','Square Table Options');
define('LEFTMENU_RECT_TABLE_OPTIONS','Rectangular Table Options');
define('LEFTMENU_BAR_OPTIONS','Bar');
define('LEFTMENU_DJ_OPTIONS','D.J');
define('LEFTMENU_DANCE_OPTIONS','Dance');
define('LEFTMENU_ADD_TEXT','Add Text');

define('PROPERTIES','Properties');
define('WIDTH','Width');
define('HEIGHT','Height');
define('CHAIR_COUNTER','Chair Counter');
define('TABLE_COUNTER','Table Counter');
define('BACKGROUND_COLOR','Background Color');
define('TABLE_COLOR','Table Color');
define('GUEST_LIST','Guest List');
define('TOTAL_GUESTS','Total guests');
define('TOTAL_SITTING','Total sitting');
define('SELECT_A_GUESTLIST','Select a Guestlist');
define('SORT','sort');
define('PRINTING','Printing');
define('CHOOSE_GUESTLIST_SORT','Choose Guestlist Sort');
define('TABLE_NUMBER','Table Number');
define('FIRST_NAME','First Name');
define('LAST_NAME','Last Name');
define('NUMBER_BOOKING','Number of Booking');
define('SORT_METHOD','Sort Method');
define('ASCENDING','Ascending');
define('DESCENDING','Descending');
define('PRINT_LIST','Print List');
define('PRINT_TICKETS','Print Tickets');
define('TABLE_NO','Table #');
define('MANAGE','Manage');
define('NUMBERING','Numbering');
define('REMOVE_ALL_BOOKING','Remove All Booking');
define('EDIT_TEXT','Edit Text');
define('TEXT','Text');
define('TEXT_COLOR','Text Color');
define('STROKE_COLOR','Stroke Color');
define('STROKE_WIDTH','Stroke Width');
define('FONT_SIZE','Font Size');
define('SAVE_TEXT','Save Text');

define('EDIT_CIRCLE_FIGURE','Edit Circle Figure');
define('EDIT_SQUARE_FIGURE','Edit Square Figure');
define('EDIT_RECTANGLE_FIGURE','Edit Rectangle Figure');
define('TRANSPARENT_FILL','Transparent Fill');
define('FILL_COLOR','Fill Color');
define('BORDER_COLOR','Border Color');
define('BORDER_WIDTH','Border Width');
define('FIGURE_RADIUS_METER','Figure Radius (Meter)');
define('SAVE_FIGURE','Save Figure');
define('FIGURE_WIDTH_HEIGHT_METER','Figure Width/Height (Meter)');
define('FIGURE_WIDTH_METER','Figure Width (Meter)');
define('FIGURE_HEIGHT_METER','Figure Height (Meter)');


define('EDIT_CIRCULAR_TABLE','Edit Circular Table');
define('EDIT_OTHER_CIRCULAR_TABLE','Edit Other Circular Table');
define('EDIT_SQUARE_TABLE','Edit Square Table');
define('EDIT_OTHER_SQUARE_TABLE','Edit Other Square Table');
define('EDIT_OTHER_RECTANGLE_TABLE','Edit Other Rectangular Table');
define('EDIT_RECTANGLE_TABLE','Edit Rectangular Table');

define('TABLE_WIDTH_METER','Table Width (Meter)');
define('TABLE_HEIGHT_METER','Table Height (Meter)');
define('TABLE_WIDTH_HEIGHT_METER','Table Width/Height (Meter)');
define('NUMBER_OF_CHAIRS','No. of Chairs');
define('TABLE_TITLE','Table title');
define('SAVE_TABLE','Save Table');
define('CHAIR_PLACEMENT_TYPE','Chair Placement type');
define('TWO_SIDED_CHAIR_PLACEMENT','2 Sided Chair Placement');
define('FOUR_SIDED_CHAIR_PLACEMENT','4 Sided Chair Placement');
define('TABLE_ALIGNMENT','Table Alignment');
define('HORIZONTAL_ALIGNMENT','Horizontal layout');
define('VERTICAL_ALIGNMENT','Vertical layout');
define('FOURTY_5_DEGREE_LAYOUT','45 Degree layout');
define('MINUS_FOURTY_5_DEGREE_LAYOUT','-45 Degree layout');

define('WELCOME_TO_TABLE_PLANNER','Welcome to Table Planner..');
define('WELCOME_TEXT','We have setup a tutorial for you if you are not familiar with our system. Take this tour and then proceed setting up your program..');
define('TAKE_THIS_TOUR','Take this tour.');
define('PROCEED_FURTHUR','Proceed furthur.');

define('NEW_PROJECT','New Project');
define('PROJECT_TITLE','Project Title');
define('PROJECT_DESC','Project Description');
define('CREATE_PROJECT','Create Project');
define('OPEN_PROJECT','Open Project');
define('CHOOSE_PROJECT','Choose Project');
define('SELECT_PROJECT','Select Project');
define('CREATED_ON','Created on');
define('SEND_PROJECT','Send Project');
define('PERSONS_NAME','Person\'s Name');
define('MOBILE','Mobile');
define('EMAIL','Email');
define('DATE_EVENT','Date Event');
define('EVENT','Event');

define('USERNAME','Username');
define('PASSWORD','Password');
define('SELECT_PROJECTS_TO_DELETE','Select Projects to Delete');
define('SELECT_ALL','Select All');
define('SELECT_NONE','Select None');
define('DESCRIPTION','DESCRIPTION');
define('TITLE','TITLE');
define('SL_NO','SL.NO.');
define('LAST_MODIFIED','Last Modified');
define('CREATED','Created');
define('PREVIEW','Preview');
define('DELETE_PROJETS','Delete Projects');
define('NAME','Name');

define('SENT_PROJECTS','Sent Projects');
define('SAVE_AS_PROJECT','Save As Project');
define('SAVE_PROJECT','Save Project');
define('MANAGE_GUESTS','Manage Guests');
define('CHOOSE_GUESTLIST','Choose Guestlist');
define('ADD_GUESTLIST','Add Guestlist');
define('SAMPLE_EXCEL','Sample Excel');
define('UPLOAD_EXCEL','Upload Excel');
define('GUEST_FIRSTNAME','GUEST FIRSTNAME');
define('GUEST_LASTNAME','GUEST LASTNAME');
define('ADULTS','Guest Verify');
define('CHILDREN','Guest Expected');
define('TEAM','Team');
define('SPECIAL_SIGN','Special Sign');
define('GUEST_PHONE','GUEST PHONE');
define('SAVE_GUESTLIST','Save GuestList');
define('ADD_GUEST','Add Guest');
define('GUESTLIST_TITLE','Guestlist Title');
define('GUESTLIST_DESCRIPTION','Guestlist Description');
define('PROJECT_SAVING_MESSAGE','Your Project is saving. Thank you for your patience...');
define('COPYRIGHT_TEXT','&copy; Copyright 2014 Eruit');
define('ACTION_FAILED',"Action Failed");
define('PROJECT_NOT_FOUND',"Project not found..");
define('INVALID_PARAMETERS_ERROR_MESSAGE', "Invalid parameters!!");
define('CANNOT_SAVE_USER_DETAILS',"Cannot save the user details.. Try again later..");
define('MAIL_MESSAGE_SENDING_FAILED', "Mail/Message sending Failed. Please try again..");
define('MAIL_MESSAGE_SENDING_SUCCESSFULL', "Mail/Message sending Successfull...");
define('UPLOADED_FILE_CORRUPTED', "Uploaded File is corrupted..");
define('UPLOADED_FILE_UNREADABLE', "Uploaded File unreadable..");
define('FILE_EXPORTED_SUCCESSFULLY', "File Exported Successfully..");
define('GENERAL_ERROR', "Failed..");
define('GENERAL_SUCCESS', "Success..");
define('HALL_NAME', "Hall Name");
define('SITTING_MANAGEMENT', "Sitting Management");
define('PARTICIPATION', "Participation");
define('BUT_SAVE', "Save");
define('BUT_CANCEL', "Cancel");
define('TOTAL_TABLES', "Total Tables");
define('TOTAL_LINES', "Total Lines");
define('NO_GUEST_ON_PROJECT', "No guest found in this project..");
define('HAVE_SIT', "HAVE SIT");
define('SENT_PROJECT_INFO_LOADING', "Sent Project Details is loading, Please wait for a moment..");
define('MESSAGE_TO_SEND_VIA_EMAIL', 'Hi #@sendToPersonName@#, This mail is to give access you to a table planner project. Visit the link <a href="#@projectLinkToSend@#">#@projectLinkToSend@#</a>. Login with Username: #@usernameToSend@# and Password: #@passwordToSend@#. Also a message is sent to you to <strong>#@sendToMobile@#</strong> mobile. Date of event #@event@# is #@date_event@#');
define('MESSAGE_TO_SEND_VIA_SMS', 'Hi #@sendToPersonName@#, This message is to give access you to a table planner project. Visit the link <a href="#@projectLinkToSend@#"></a>. Login with Username: #@usernameToSend@# and Password: #@passwordToSend@#. Also an email is sent to you to <strong>#@sendToEmail@#</strong> email address.');

$JS_MESSAGES_STR = array(
	'PROJECT_LOADING_MESSAGE' => "Your project is loading... Please wait for a moment...",
	'PROJECT_SAVING_MESSAGE' => PROJECT_SAVING_MESSAGE,
	'INTERNAL_ERROR' => "Internal error.. Try again..",
	'NO_PROJECT_SENT' => "No Project sent still...",
	'REMOVE_ALL_BOOKING_CONF' => "Ary you sure you want to remove all booking from this project?",
	'TABLE_NUMBER_REARRANGE_ENABLED_INFO' => "Table numbering re-arrange is enabled.. Click on tables to number them serially..",
	'CHOOSE_A_FILE_TO_UPLOAD' => "Please choose a file to upload..",
	'CHOOSE_PROPER_FILE_TO_UPLOAD' => "Please choose a proper file to upload..",
	'CHOOSE_A_GUESTLIST_TO_EXPORT' => "Choose a guestlist to export excel sheet..",
	'EXCEL_FILE_CONTENT_SAVED' => "Excel file content is saved successfully..",
	'EXCEL_FILE_PROCESSED_DIALOG' => "Your file is being processed.. Please Wait for some time..",
	'FILE_API_NOT_SUPPORTED' => "The File APIs are not fully supported in this browser.",
	'ONE_GUESTLIST_ASSIGNED_TO_PROJECT' => "Already one guestlist is assigned with this current project..",
	'NO_PROJECT_OPEN_FOR_SENDING' => "No Project is open for sending",
	'NO_PROJECT_OPEN_FOR_PRINTING' => "No Project is open for printing",
	'DEFAULT_ADDED_TEXT_CONTENT' => "This is your text... ",
	'PROJECT_DELETE_CONFIRM_MESSAGE' => "Are you sure you want to delete this project?",
	'NO_RECORD_TO_INSERT' => "No record to insert.. skipped..",
	'CANNOT_DELETE_PREVIOUS_RECORDS' => "cannot delete previous records... error in delete query...",
	'GUESTLIST_DATA_SAVED_SUCCESSFULLY' => "Guestlist data saved successfully..",
	'ERROR_SAVING_DATA_TRY_AGAIN' => "Error saving data.. Please try again..",
	'NO_ITEM_FOUND_FOR_PRINTING' => "No items found for printing.. Please try again..",
	'ERROR_LOADING_DATA_TRY_AGAIN' => "Error loading data.. Please try again..",
	'SELECT_A_GUESTLIST' => SELECT_A_GUESTLIST,
	'PROJECT_SAVED_SUCCESSFULY' => "Project Saved SuccesfullY..",
	'PROJECT_CLOSE_CONFIRM_DIALOG' => "Are you sure, you want to close?",
	'UNTITLED_PROJECT_NAME' => UNTITLED_PROJECT_NAME,
	'ACTION_FAILED' => ACTION_FAILED,
	'CHANGES_SAVED_SUCCESSFULLY_MESSAGE' => "Changes saved succesfull..",
	'PROJECT_RELATED_FILE_NOT_FOUND' => "Project file not found on server..",
	'SOME_ERROR_OCCURRED_MESSAGE' => "Some error occured. Please try again later..",
	'PROJECT_DELETED_SUCCESSFULLY_MESSAGE' => "Project deleted successfully.",
	'PROJECTS_DELETED_SUCCESSFULLY_MESSAGE' => "Projects deleted succesfully..",
	'SELECT_PROJECT_TO_BE_DELETED' => "Please select project to delete..",
	'SELECT_A_PROJECT' => "Select Project",
	'UNSAVED_CHANGES_BEFORE_CLOSE_CONFIRM' => "There are unsaved changes in current project. Would you like to create a new project. This will reject all the changes made to the old project. Are you sure you want t continue?",
	'UPDATED_MEASUREMENT_CHANGE_MESSAGE' => "This page will reload to apply changes.. This property cannot be applied in current project. Are you sure you want to proceed?",
	'ODD_NUMBER_CHAIRS_CANNOT_BE_PLACED' => "Odd number of chairs cannot be placed here...",
	'NO_ROOM_FOR_THIS_MANY_CHAIRS' => "No Room to place this many chairs...",
	'CONTEXTMENU_QUIT' => "Quit",
	'CONTEXTMENU_COPY' => "Copy",
	'CONTEXTMENU_EDIT' => "Edit",
	'CONTEXTMENU_DELETE' => "Delete",
	'CONTEXTMENU_REMOVE_BOOKING' => "Remove Booking",
	'TEXT_UPDATE_FAILED' => "Text update failed !! error :: ",
	'TEXT_UPDATED_SUCCESSFULLY_MESSAGE' => "Text updated successfully",
	'FIGURE_UPDATE_FAILED' => "Figure update failed !! error :: ",
	'FIGURE_UPDATED_SUCCESSFULLY_MESSAGE' => "Figure updated successfully",
	'TABLE_WIDTH_HEIGTH_MUST_GREATER_THAN_THIS' => "Table Width/Height must be greater than this..",
	'RECTANGULAR_TABLE_UPDATED_MESSAGE' => "rectangular table updated",
	'TABLE_WIDTH_MUST_GREATER_THAN_THIS' => "Table Width must be greater than this..",
	'TABLE_HEIGHT_MUST_GREATER_THAN_THIS' => "Table Height must be greater than this..",
	'SQUARE_TABLE_UPDATED_SUCCESSFULLY_MESSAGE' => "Square Table Updated Successfully..",
	'CIRCLE_TABLE_UPDATED_SUCCESSFULLY_MESSAGE' => "Circular Table Updated Successfully..",
	'CANNOT_PLACE_THIS_MANY_CHAIRS' => "Cannot place this many chairs in this table..",
	'ELEMENT_REMOVE_CONFIRMATION_MESSAGE' => "Are you sure you want to remove this element?",
	'INVALID_DATA_ERROR_MESSAGE' => "Invalid data!! Please try again..",
	'INVALID_PARAMETERS_ERROR_MESSAGE' => "Invalid parameters!! Please try again..",
	'PAGE_LEAVE_MESSAGE' => 'You sure you want to leave?',
	'CANNOT_UPDATE_USER_DETAILS_ERROR' => "Cannot update user details...",
	'SENT_PROJECT_INFO_LOADING' => SENT_PROJECT_INFO_LOADING,
	'ERROR_SAVING_DATA_RECORD_WITH_SAME_NAME' => "Error saving data.. Project with save name exists..",
	'ONLY_ENGLISH_ONLY_IN_USERNAME_PASSWORD' => "Cannot send non-English content as Username/Password",
);
?>