<?php
define('MENU_NEW','חדש');
define('MENU_OPEN','פתח');
define('MENU_SAVE','שמור');
define('MENU_SAVE_AS','שמור בשם');
define('MENU_DELETE','מחק');
define('MENU_SEND_PROJECT','שלח פרויקט');
define('MENU_SENT_ITEM','פריט שנשלח');
define('MENU_PRINT','הדפסה');
define('MENU_LOGOUT','התנתק');

define('ZOOM','ZOOM');
define('UNTITLED_PROJECT_NAME','ללא שם');

define('LEFTMENU_ADD_TABLE','הוסף שולחן');
define('LEFTMENU_CIRCULAR_TABLE','שולחן עגול');
define('LEFTMENU_SQUARE_TABLE','שולחן מרובע');
define('LEFTMENU_RECTANGULAR_TABLE','שלוחן מלבני');

define('LEFTMENU_ADD_FIGURE','הוסף צורה');
define('LEFTMENU_CIRCULAR_FIGURE','עגול');
define('LEFTMENU_SQUARE_FIGURE','ריבוע');
define('LEFTMENU_RECTANGULAR_FIGURE','מלבן');

define('LEFTMENU_ADD_OTHER_TABLE','אובייקטים נוספים');

define('LEFTMENU_CIRCLE_TABLE_OPTIONS','אובייקט עגול');
define('LEFTMENU_SQUARE_TABLE_OPTIONS','אובייקט מרובע');
define('LEFTMENU_RECT_TABLE_OPTIONS','אפשרויות טבלה מלבניות');
define('LEFTMENU_BAR_OPTIONS','בר');
define('LEFTMENU_DJ_OPTIONS','עמדת DJ');
define('LEFTMENU_DANCE_OPTIONS','רחבת ריקודים');
define('LEFTMENU_ADD_TEXT','הוספת טקסט');

define('PROPERTIES','מאפיינים');
define('WIDTH','אורך');
define('HEIGHT','רוחב');
define('CHAIR_COUNTER','כסאות');
define('TABLE_COUNTER','שולחנות');
define('BACKGROUND_COLOR','צבע רקע');
define('TABLE_COLOR','צבע שולחן');
define('GUEST_LIST','רשימת מוזמנים');
define('TOTAL_GUESTS','לא יושבים');
define('TOTAL_SITTING','יושבים');
define('SELECT_A_GUESTLIST','בחר רשימת מוזמנים');
define('SORT','מיון');
define('PRINTING','הדפסה');
define('CHOOSE_GUESTLIST_SORT','בחר מיון לרשימה');
define('TABLE_NUMBER','מספר שולחן');
define('FIRST_NAME','שם');
define('LAST_NAME','משפחה');
define('NUMBER_BOOKING','מספר מוזמנים');
define('SORT_METHOD','צורת מיון');
define('ASCENDING','מיון עולה');
define('DESCENDING','מיון יורד');
define('PRINT_LIST','הדפסת רשימה');
define('PRINT_TICKETS','הדפסת תגיות');
define('TABLE_NO','שולחן #');
define('MANAGE','ערוך רשימה');
define('NUMBERING','מספור');
define('REMOVE_ALL_BOOKING','החזר מוזמנים לרשימה');
define('EDIT_TEXT','ערוך טקסט');
define('TEXT','טקסט');
define('TEXT_COLOR','צבע טקסט');
define('STROKE_COLOR','צבע הדגשה');
define('STROKE_WIDTH','רוחב הדגשה');
define('FONT_SIZE','גודל פונט');
define('SAVE_TEXT','שמור טקסט');

define('EDIT_CIRCLE_FIGURE','ערוך צורה עגולה');
define('EDIT_SQUARE_FIGURE','ערוך צורת ריבוע');
define('EDIT_RECTANGLE_FIGURE','ערוך צורת מלבן');
define('TRANSPARENT_FILL','שקוף');
define('FILL_COLOR','מלא צבע');
define('BORDER_COLOR','צבע מסגרת');
define('BORDER_WIDTH','רוחב מסגרת');
define('FIGURE_RADIUS_METER','רדיוס צורה במטר');
define('SAVE_FIGURE','שמור צורה');
define('FIGURE_WIDTH_HEIGHT_METER','אורך ורוחב הצורה במטר');
define('FIGURE_WIDTH_METER','אורך צורה במטר');
define('FIGURE_HEIGHT_METER','רוחב צורה במטר');


define('EDIT_CIRCULAR_TABLE','ערוך שולחן עגול');
define('EDIT_OTHER_CIRCULAR_TABLE','ערוך שולחן עגול אחר');
define('EDIT_SQUARE_TABLE','ערול שולחן מרובע');
define('EDIT_OTHER_SQUARE_TABLE','ערוך שולחן מרובע אחר');
define('EDIT_OTHER_RECTANGLE_TABLE','שולחן לערוך את אחר מלבני');
define('EDIT_RECTANGLE_TABLE','ערוך שולחן מלבני');

define('TABLE_WIDTH_METER','אורך שולחן במטר');
define('TABLE_HEIGHT_METER','רוחב שולחן במטר');
define('TABLE_WIDTH_HEIGHT_METER','אורך ורוחב שולחן במטר');
define('NUMBER_OF_CHAIRS','מספר כסאות');
define('TABLE_TITLE','כותרת השולחן');
define('SAVE_TABLE','שמור שולחן');
define('CHAIR_PLACEMENT_TYPE','מיקום כסאות');
define('TWO_SIDED_CHAIR_PLACEMENT','כסאות בשני צדדים');
define('FOUR_SIDED_CHAIR_PLACEMENT','כסאות בארבעה צדדים');
define('TABLE_ALIGNMENT','הצמדת שולחן');
define('HORIZONTAL_ALIGNMENT','פריסה אופקית');
define('VERTICAL_ALIGNMENT','פריסה אנכית');
define('FOURTY_5_DEGREE_LAYOUT','סובב 45 מעלות ימינה');
define('MINUS_FOURTY_5_DEGREE_LAYOUT','סובב 45 מעלות שמאלה');

define('WELCOME_TO_TABLE_PLANNER','ברוך הבא לאירועית סידור שולחנות');
define('WELCOME_TEXT','אם אתה לא מכיר את המערכת שלנו, אז יש לנו סיור עם הדרכה מהירה עבורך . הכנס לסיור ולאחר מכן תתחיל בבניית הפרוייקט שלך...');
define('TAKE_THIS_TOUR','הכנס לסיור');
define('PROCEED_FURTHUR','דלג על שלב זה');

define('NEW_PROJECT','פרוייקט חדש');
define('PROJECT_TITLE','שם הפרוייקט');
define('PROJECT_DESC','תיאור הפרוייקט');
define('CREATE_PROJECT','יצירת הפרוייקט');
define('OPEN_PROJECT','פתח פרוייקט');
define('CHOOSE_PROJECT','בחר פרוייקט');
define('SELECT_PROJECT','בחירת פרוייקט');
define('CREATED_ON','נוצר ב');
define('SEND_PROJECT','שליחת פרוייקט');
define('PERSONS_NAME','שם\'s Name');
define('MOBILE','נייד');
define('EMAIL','דוא"ל');
define('DATE_EVENT','תאריך אירוע');
define('EVENT','סוג אירוע');

define('USERNAME','שם משתמש');
define('PASSWORD','סיסמה');
define('SELECT_PROJECTS_TO_DELETE','בחר פרוייקט למחיקה');
define('SELECT_ALL','בחר הכל');
define('SELECT_NONE','לא נבחר');
define('DESCRIPTION','תיאור');
define('TITLE','כותרת');
define('SL_NO','סידורי');
define('LAST_MODIFIED','השתנה לאחרונה');
define('CREATED','נוצר ב');
define('PREVIEW','תצוגה מקדימה');
define('DELETE_PROJETS','מחק פרוייקט');
define('NAME','שם');

define('SENT_PROJECTS','פרוייקטים שנשלחו');
define('SAVE_AS_PROJECT','שמור בשפ');
define('SAVE_PROJECT','שמור');
define('MANAGE_GUESTS','ניהול מוזמנים');
define('CHOOSE_GUESTLIST','בחר רשימת מוזמנים');
define('ADD_GUESTLIST','הוסף רשימת מוזמנים');
define('SAMPLE_EXCEL','דוגמה לקובץ אקסל');
define('UPLOAD_EXCEL','ייבא מקובץ אקסל');
define('GUEST_FIRSTNAME','שם');
define('GUEST_LASTNAME','משפחה');
define('ADULTS','אישרו הגעה');
define('CHILDREN','צפי אורחים');
define('TEAM','צוות');
define('SPECIAL_SIGN','סימון מיוחד');
define('GUEST_PHONE','טלפון');
define('SAVE_GUESTLIST','שמור רשימה');
define('ADD_GUEST','הוסף מוזמן');
define('GUESTLIST_TITLE','כותרת הרשימה');
define('GUESTLIST_DESCRIPTION','תיאור הרשימה');
define('PROJECT_SAVING_MESSAGE','הפרוייקט נשמר... תודה על הסבלנות');
define('COPYRIGHT_TEXT','כל הזכויות שמורות לאירועית - סימן מסחרי רשום');
define('ACTION_FAILED',"הפעולה נכשלה");
define('PROJECT_NOT_FOUND',"לא נמצא פרוייקט");
define('INVALID_PARAMETERS_ERROR_MESSAGE', "הפרטים לא חוקיים!!!");
define('CANNOT_SAVE_USER_DETAILS',"לא ניתן לשמור את פרטי המשתמש .. נסה שוב מאוחר יותר ..");
define('MAIL_MESSAGE_SENDING_FAILED', "שליחת הודעת דואל נכשלה. נסה ושב מאוחר יותר...");
define('MAIL_MESSAGE_SENDING_SUCCESSFULL', "הודעת דואל נשלח בהצלחה");
define('UPLOADED_FILE_CORRUPTED', "הקובץ שהועלה פגום...");
define('UPLOADED_FILE_UNREADABLE', "אין אפשרות לקרוא את הקובץ");
define('FILE_EXPORTED_SUCCESSFULLY', "ייצוא הקובץ הצליח...");
define('GENERAL_ERROR', "נכשל...");
define('GENERAL_SUCCESS', "בוצע...");
define('HALL_NAME', "שם האולם");
define('SITTING_MANAGEMENT', "ניהול סידורי ישיבה");
define('PARTICIPATION', "אישורי הגעה");
define('BUT_SAVE', "שמור");
define('BUT_CANCEL', "לבטל");
define('TOTAL_TABLES', "סה\"כ שולחנות");
define('TOTAL_LINES', "סה\"כ קווים");
define('NO_GUEST_ON_PROJECT', "אין אורח שנמצא בפרויקט הזה ..");
define('HAVE_SIT', "שיהיה לך SIT");
define('SENT_PROJECT_INFO_LOADING', "Sent Project Details is loading, Please wait for a moment..");
define('MESSAGE_TO_SEND_VIA_EMAIL', 'Hi #@sendToPersonName@#, This mail is to give access you to a table planner project. Visit the link <a href="#@projectLinkToSend@#">#@projectLinkToSend@#</a>. Login with Username: #@usernameToSend@# and Password: #@passwordToSend@#. Also a message is sent to you to <strong>#@sendToMobile@#</strong> mobile. Date of event #@event@# is #@date_event@#');
define('MESSAGE_TO_SEND_VIA_SMS', 'Hi #@sendToPersonName@#, This message is to give access you to a table planner project. Visit the link <a href="#@projectLinkToSend@#"></a>. Login with Username: #@usernameToSend@# and Password: #@passwordToSend@#. Also an email is sent to you to <strong>#@sendToEmail@#</strong> email address.');

$JS_MESSAGES_STR = array(
	'PROJECT_LOADING_MESSAGE' => "הפרויקט שלך בטעינה ... אנא המתן...",
	'PROJECT_SAVING_MESSAGE' => PROJECT_SAVING_MESSAGE,
	'INTERNAL_ERROR' => "שגיאה פנימית... נסה שוב...",
	'NO_PROJECT_SENT' => "הפרוייקט עדיין לא נשלח",
	'REMOVE_ALL_BOOKING_CONF' => "האם אתה בטוח שאתה רוצה להחזיר לרשימה את כל המוזמנים שהושבת?",
	'TABLE_NUMBER_REARRANGE_ENABLED_INFO' => "מיספור שולחנות לארגון מחדש מופעל... לחץ על השולחנות למיספור מחדש...",
	'CHOOSE_A_FILE_TO_UPLOAD' => "בחר קובץ לטעינה...",
	'CHOOSE_PROPER_FILE_TO_UPLOAD' => "בחר קובץ נכון לטעינה...",
	'CHOOSE_A_GUESTLIST_TO_EXPORT' => "בחר רשימה לייצא גיליון אקסל ",
	'EXCEL_FILE_CONTENT_SAVED' => "תוכן קובץ אקסל נשמר בהצלחה...",
	'EXCEL_FILE_PROCESSED_DIALOG' => "הקובץ שלך נמצא בעיבוד... אנא המתן...",
	'FILE_API_NOT_SUPPORTED' => "המערכת אינה תומכת בקובץ זה",
	'ONE_GUESTLIST_ASSIGNED_TO_PROJECT' => "אורח שובץ",
	'NO_PROJECT_OPEN_FOR_SENDING' => "לא נמצא פרוייקט למשלוח",
	'NO_PROJECT_OPEN_FOR_PRINTING' => "לא נמצא פרוייקט להדפסה",
	'DEFAULT_ADDED_TEXT_CONTENT' => "זה הטקסט שלך",
	'PROJECT_DELETE_CONFIRM_MESSAGE' => "האם הנך בטוח למחוק פרוייקט זה  ?",
	'NO_RECORD_TO_INSERT' => "לא נמצאה רשומה לעדכון..",
	'CANNOT_DELETE_PREVIOUS_RECORDS' => "אין אפשרות למחוק רשומות קודמות...",
	'GUESTLIST_DATA_SAVED_SUCCESSFULLY' => "רשימת מוזמנים נרשמה בהצלחה ...",
	'ERROR_SAVING_DATA_TRY_AGAIN' => "אירעה תקלה בשמירת קובץ ...",
	'NO_ITEM_FOUND_FOR_PRINTING' => "לא נמצאו פריטים להדפסה...",
	'ERROR_LOADING_DATA_TRY_AGAIN' => "אירעה שגיאה בטעינת הקובץ ,אנא נסה שוב...",
	'SELECT_A_GUESTLIST' => SELECT_A_GUESTLIST,
	'PROJECT_SAVED_SUCCESSFULY' => "הפרוייקט נרשם בהצלחה ...",
	'PROJECT_CLOSE_CONFIRM_DIALOG' => "האם ברצונך לעזוב פרוייקט זה ?",
	'UNTITLED_PROJECT_NAME' => UNTITLED_PROJECT_NAME,
	'ACTION_FAILED' => ACTION_FAILED,
	'CHANGES_SAVED_SUCCESSFULLY_MESSAGE' => "השינויים נשמרו בהצלחה  ....",
	'PROJECT_RELATED_FILE_NOT_FOUND' => "שם פרוייקט המצויין לא נמצא ...",
	'SOME_ERROR_OCCURRED_MESSAGE' => "שגיאה לא מוכרת ,  אנא נסה שוב ...",
	'PROJECT_DELETED_SUCCESSFULLY_MESSAGE' => "הפרוייקט בוטל בהצלחה ...",
	'PROJECTS_DELETED_SUCCESSFULLY_MESSAGE' => "הפרוייקט בוטל בהצלחה ...",
	'SELECT_PROJECT_TO_BE_DELETED' => "בחר הקובץ הרצוי למחיקה ...",
	'SELECT_A_PROJECT' => "בחר פרוייקט",
	'UNSAVED_CHANGES_BEFORE_CLOSE_CONFIRM' => "אירועים אחרונים עדיין לא נשמרו, האם ברצונך לעזוב לפני שמירת הנתונים ?",
	'UPDATED_MEASUREMENT_CHANGE_MESSAGE' => "לא ניתן ליישם מידות אלו, האם להמשיך ?",
	'ODD_NUMBER_CHAIRS_CANNOT_BE_PLACED' => "מספר כיסאות אנו זוגי ...",
	'NO_ROOM_FOR_THIS_MANY_CHAIRS' => "אין מרחב מתאים לכמות הכסאות ...",
	'CONTEXTMENU_QUIT' => "יציאה",
	'CONTEXTMENU_COPY' => "העתק",
	'CONTEXTMENU_EDIT' => "ערוך",
	'CONTEXTMENU_DELETE' => "מחק",
	'CONTEXTMENU_REMOVE_BOOKING' => "מחק מרשימה",
	'TEXT_UPDATE_FAILED' => "אירעה שגיאה ברישום",
	'TEXT_UPDATED_SUCCESSFULLY_MESSAGE' => "נרשם בהצלחה ...",
	'FIGURE_UPDATE_FAILED' => "אירעה שגיאה בעדכון הצורה ...",
	'FIGURE_UPDATED_SUCCESSFULLY_MESSAGE' => "רישום הצורה נרשם בהצלחה ...",
	'TABLE_WIDTH_HEIGTH_MUST_GREATER_THAN_THIS' => "אורך / רוחב השולחן חייב להיות גדול יותר ...",
	'RECTANGULAR_TABLE_UPDATED_MESSAGE' => "רישום שולחן מלבני עבר בהצלחה ",
	'TABLE_WIDTH_MUST_GREATER_THAN_THIS' => "אורך / רוחב השולחן חייב להיות גדול יותר ...",
	'TABLE_HEIGHT_MUST_GREATER_THAN_THIS' => "גובה שולחן צריך להיות גדול יותר מזה ..",
	'SQUARE_TABLE_UPDATED_SUCCESSFULLY_MESSAGE' => "רישום שולחן מרובע עבר בהצלחה",
	'CIRCLE_TABLE_UPDATED_SUCCESSFULLY_MESSAGE' => "רישום שולחן עגול עבר בהצלחה",
	'CANNOT_PLACE_THIS_MANY_CHAIRS' => "אין אפשרות למקם את כמות הכיסאות ...",
	'ELEMENT_REMOVE_CONFIRMATION_MESSAGE' => "האם אתה בטוח שברצונך למחוק אלמנט זה ?",
	'INVALID_DATA_ERROR_MESSAGE' => "נתונים שגויים ... אנא נסה שוב",
	'INVALID_PARAMETERS_ERROR_MESSAGE' => "פרמטרים שגויים ... אנא נסה שוב ",
	'PAGE_LEAVE_MESSAGE' => 'האם הנך בטוח שברצונך לעזוב דף זה ?',
	'CANNOT_UPDATE_USER_DETAILS_ERROR' => "אירעה שגיאה בעדכון פרטי המשתמש ...",
	'SENT_PROJECT_INFO_LOADING' => SENT_PROJECT_INFO_LOADING,
	'ERROR_SAVING_DATA_RECORD_WITH_SAME_NAME' => "נתוני שגיאה בשמירה .. פרויקט עם להציל שם קיים ..",
	'ONLY_ENGLISH_ONLY_IN_USERNAME_PASSWORD' => "לא ניתן לשלוח תוכן שאינה באנגלית כשם משתמש / סיסמא",
);
?>